spring:
  application:
    name: realworld
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/real-world;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view : false

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080

jwt:
  #realworld_example_study_group_backend_app
  secret: "cmVhbHdvcmxkX2V4YW1wbGVfc3R1ZHlfZ3JvdXBfYmFja2VuZF9hcHA="
