server:
  port: 8080

spring:
  profiles:
    active: h2

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
