### Send POST sign in member
POST http://localhost:8080/api/member/signin
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "jhj",
  "password": "1111",
  "email" : "jhj@example.com"
}


### Send POST request with json body
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "jhj",
  "password": "1111"
}

### Send POST request with json body
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "jhj",
  "password": "111"
}

